name: Dev Branch CI

on:
  push:
    branches-ignore:
      - 'master'
      - 'release*'

jobs:

  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2.5.0
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B clean install -P full
