name: Master Branch CI

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2.1.7
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn -B clean install -Pfull

      - name: SonarCloud Scan
        run: mvn -B sonar:sonar -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ./moviebuffs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'
      - name: Package with Maven
        run: mvn -B clean install -DskipTests --file pom.xml
        
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dockertmt/moviebuffs
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          workdir: ./moviebuffs
          default_branch: master
          tags: "latest"
          buildoptions: "--compress --force-rm"
